### ISSUE TITLE
[Request] Re-implement default HashMap session handler for finetuning

### ISSUE THREAD

**Issue by weewoo-meow** [tipsy/javalin-jetty-sessions-example#1]
I have the current issue that I don't know how to implement the same same session handler Javalin uses when it boots up (HashMap in RAM).

The reason I want to do a reimplementation is, so I can set specific properties to it like a custom expiry policy or even expose the session hashmap to my codebase.

**Comment by tipsy** [comment]
The default session handler is defined here:

https://github.com/tipsy/javalin/blob/master/javalin/src/main/java/io/javalin/jetty/JettyServer.kt#L91

**Comment by weewoo-meow** [comment]
Thanks, I will look how I can do it in Java. It would be nice for other users to extend the Javalin session tutorial explaining how to do this.

**Comment by tipsy** [comment]
> Thanks, I will look how I can do it in Java.

```java
SessionHandler sessionHandler = new SessionHandler();
sessionHandler.setHttpOnly(true);
```

> It would be nice for other users to extend the Javalin session tutorial explaining how to do this.

Feel free to submit a PR :)
